/*
 * MedicoSoft (c) 2019
 * Made under Proprietary license
 */

 

    
    // Configuration service 
    //GET_CONFIGURATION_DEVICE: 'GET_CONFIGURATION_DEVICE',
    //GET_CONFIGURATION_ALL_DEVICES: 'GET_CONFIGURATION_ALL_DEVICES'

    // Measurement service
    /*
    GET_CONFIGURATION_DEVICE: 'GET_CONFIGURATION_DEVICE',
    GET_CONFIGURATION_DEVICE: 'GET_CONFIGURATION_DEVICE',
    GET_CONFIGURATION_DEVICE: 'GET_CONFIGURATION_DEVICE',
    GET_CONFIGURATION_DEVICE: 'GET_CONFIGURATION_DEVICE',
    GET_CONFIGURATION_DEVICE: 'GET_CONFIGURATION_DEVICE',
    GET_CONFIGURATION_DEVICE: 'GET_CONFIGURATION_DEVICE',
    GET_CONFIGURATION_DEVICE: 'GET_CONFIGURATION_DEVICE'
    */
    // Map
// Constants actions

// Measurementes service - GET MeasurementsData
export const MEASUREMENT_GET_MEASUREMENTSDATA_START = "MEASUREMENT_GET_MEASUREMENTSDATA_START";
export const MEASUREMENT_GET_MEASUREMENTSDATA_ERROR = "MEASUREMENT_GET_MEASUREMENTSDATA_ERROR";
export const MEASUREMENT_GET_MEASUREMENTSDATA_COMPLETE = "MEASUREMENT_GET_MEASUREMENTSDATA_COMPLETE";